extraction:
  frequency_days: 1
  groups:

    # - username: "@codechef_answers"
    #   name: "My Promotions"

    # - username: "@my_promotions"
    #   name: "My Promotions"

    - username: "@leetcode_answers"
      name: "LeetCode Answers"



 

dm_limits:
  max_per_day: 3

promotion_channel: "Jobs_Lelo"
